-- ADD STAGE-SPECIFIC DEADLINES TO PROJECTS
ALTER TABLE projects 
ADD COLUMN discovery_deadline TIMESTAMP WITH TIME ZONE,
ADD COLUMN seo_deadline TIMESTAMP WITH TIME ZONE,
ADD COLUMN dev_deadline TIMESTAMP WITH TIME ZONE,
ADD COLUMN qa_deadline TIMESTAMP WITH TIME ZONE,
ADD COLUMN delivery_deadline TIMESTAMP WITH TIME ZONE;
